Repository ifocorporation/ifo-corporation-client, pull requests merged in 2023-03, with the labels that each got.

#7 [TS-19]: Set Up React-Vite TypeScript for the IFO Corporation Project
  .gitignore
  README.md
  index.html
  package.json
  public/vite.svg
  src/App.css
  src/App.tsx
  src/assets/react.svg
  src/index.css
  src/main.tsx
  src/vite-env.d.ts
  test.html
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
  yarn.lock
Labels: bug

#8 [TS-19]: Set Up React-Vite TypeScript for the IFO Corporation Project
  .gitignore
  README.md
  index.html
  package.json
  public/vite.svg
  src/App.css
  src/App.tsx
  src/assets/react.svg
  src/index.css
  src/main.tsx
  src/vite-env.d.ts
  test.html
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
  yarn.lock
Labels: bug

#13 [IMP-7]: Setting Up the Folder Structure, File Structure and Remove useless JS codes from the Files
  client/public/vite.svg
  client/src/App.css
  client/src/App.tsx
  client/src/assets/react.svg
  client/src/index.css
Labels: feature

#14 Setting Up the Folder Structure, File Structure and Remove useless JS codes from the Files
  .github/workflows/node.js.yml
  client/.gitignore
  client/package.json
  client/public/vite.svg
  client/src/App.css
  client/src/App.tsx
  client/src/assets/react.svg
  client/src/index.css
  client/vite.config.ts
  client/yarn.lock
Labels: bug, feature
