Repository ifocorporation/ifo-corporation-client, pull requests merged in 2023-01, with the labels that each got.

#2 Update Readme.md
  README.md
  index.html
Labels: documentation

#1 [TS-2]: Set and write GitFlow instructions and branch activity rules on Github Wiki
  index.html
Labels: feature

#5 [TS-3] Hotfix Testing
  test.html
Labels: hotfix
